-- ─── MUN Guardian — migration 002 ────────────────────────────────────────────
-- Allow explicit seq values in audit_log so the hash chain can compute a
-- deterministic seq (prev.seq + 1) BEFORE insert. The table forbids UPDATE
-- (immutability trigger), so the hash must be computed with the final seq in a
-- single INSERT. GENERATED BY DEFAULT permits an explicit value while still
-- auto-generating one when seq is omitted. Appends are serialised by an
-- advisory lock (see audit/service.ts), so seq stays monotonic.
ALTER TABLE audit_log ALTER COLUMN seq SET GENERATED BY DEFAULT;
